name: Build + Deploy
on: 
  push:
    branches:
    - master

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102

    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.github_token}}

    - name: Build with dotnet
      run: dotnet build --configuration Release /p:AssemblyVersion=0.0.${{ steps.buildnumber.outputs.build_number }},Version=0.0.${{ steps.buildnumber.outputs.build_number }}

    - name: Run unit tests
      run: dotnet test --configuration Release --no-build

    - name: Push Nugets
      run: dotnet nuget push src/Sandra.Templating/bin/Release/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
